:name: marker_rainbow
:description: marker with rainbow color
:ndims: 1
:nvars: 2
:vizshot_method: marker_rainbow
:script: |
  newfrm = opt.delete(:newfrm)
  if opt.delete(:exchange)
    GGraph::color_scatter(gphys, gphys.axis(0).to_gphys, gphys1, newfrm, opt)
  else
    GGraph::color_scatter(gphys.axis(0).to_gphys, gphys, gphys1, newfrm, opt)
  end

:setting_html: |
  <%
  @order_type = "marker_rainbow"
  @order_names = %w(Marker Color)
  @num_for_each = 2
  @group_name = "diagram"
  @order = @analysis.draw_variables_order
  %>
  <div>
    Variables for Maker and Color
    <%= render(:partial => "variables_order") %>
    <br/>
    <%= check_box("analysis", "marker_rainbow_exchange") %>
    <label for="analysis_marker_rainbow_exchange">Exchange x and y</label>
  </div>
:options:
- :name: exchange
  :default: false
  :type: boolean
  :parser: vizshot
  :description: "exchange abscissa and ordinate"

