#!/usr/bin/env ruby
require "find"
include Find

top = File.dirname(__FILE__) + '/..'
Dir.chdir( top )

print "cleaning tmp/ and public/diagram/ ...\n"
system('rm -f `find tmp/sessions tmp/work public/diagrams -atime +1 -type f -print`')
system('rm -fr `find tmp/work/* public/diagrams/* -type d -empty -print`')

