# 表題	dcnote Makefile テンプレート
# Copyright (C) GFD_Dennou_Club, 2000.  All rights reserved.
#
# 履歴  1999/07/21  小高正嗣, 林祥介, 
#       1999/11/20  竹広真一
#       2000/01/15  杉山耕一朗
#       2000/04/11  竹広真一
#
##################################################################
#
# tex ソースのメインファイル名(原始資源が tex の場合)
#
TARGET=eq_diffusion
#
# 資源名と資源トップディレクトリ
## PTOPDIRNAME として英語名を使う場合はダブルクオートで囲むこと
#
PTOPDIRNAME ="2 次元円盤領域での拡散型方程式の解析解"
PTOPDIR =/GFD_Dennou_Club/ftp/arch/spmodel/2d-disk-eq/diffusion
#PTOPDIR =/GFD_Dennou_Club/dc-arch/riron/renzoku/gaisetu
#
#PTOPDIRNAME ="Matsuno (1966)"
#PTOPDIR =/GFD_Dennou_Club/ftp/arch/reviews/zz1966/matsuno
#PTOPDIR =/GFD_Dennou_Club/dc-arch/reviews/zz1966/matsuno
#
################
# $(DCNOTE-MKINDEX) のオプション; html ファイルのリンク先表題
# 
# プロジェクト名とプロジェクトトップディレクトリ
## TOPDIRNAME として英語名を使う場合はダブルクオートで囲むこと
#
TOPDIRNAME = "スペクトルモデルプロジェクト(spmodel)"
TOPDIR =/GFD_Dennou_Club/ftp/arch/spmodel
#TOPDIR =/GFD_Dennou_Club/dc-arch/riron
#
#TOPDIRNAME =地球流体読書ノート
#TOPDIR =/GFD_Dennou_Club/ftp/arch/reviews
#TOPDIR =/GFD_Dennou_Club/dc-arch/reviews
# 
##################################################################
# 前提条件
#
# 現在の作業ディレクトリ
#
WORKDIR=$(PTOPDIR)/src 
#
# 生成物のインストール先
#
TARGETDIR=../pub
##################################################################

include ./Mkinclude

