#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"
MIRROR_BOOTSTRAP=${MIRROR_DEBIAN}
MIRROR_VOLATILE=${MIRROR_DEBIAN}
MIRROR_BACKPORTS="http://backports.debian.org/debian-backports/"

DISTRIBUTION="squeeze"
ARCH="i386"
MODE="debian"
BOOTAPPEND_LIVE="persistent splash noautologin"

lb config noauto \
	--apt-recommends true \
	--archive-areas "main contrib non-free" \
	--architecture "${ARCH}" \
	--backports true \
	--binary-images iso-hybrid  \
	--bootappend-live "${BOOTAPPEND_LIVE}" \
	--bootloader syslinux \
	--debian-installer live \
	--debian-installer-distribution "${DISTRIBUTION}" \
	--iso-publisher "GFD Dennou Club; http://www.gfd-dennou.org/;" \
	--linux-flavours 686 \
	--mirror-binary "${MIRROR_DEBIAN}" \
	--mirror-binary-security "${MIRROR_SECURITY}" \
	--mirror-binary-volatile "${MIRROR_VOLATILE}" \
	--mirror-binary-backports "${MIRROR_BACKPORTS}" \
	--mirror-bootstrap "${MIRROR_BOOTSTRAP}" \
	--mirror-chroot "${MIRROR_DEBIAN}" \
	--mirror-chroot-security "${MIRROR_SECURITY}" \
	--mirror-chroot-volatile "${MIRROR_VOLATILE}" \
	--mirror-chroot-backports "${MIRROR_BACKPORTS}" \
	--mode "${MODE}" \
	--security true \
	--tasks "japanese japanese-desktop laptop desktop xfce-desktop" \
	--tasksel aptitude \
	--volatile true \
	--win32-loader true \
	-d "${DISTRIBUTION}" \
	-l ja \
	${@}
