#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"
MIRROR_BOOTSTRAP=${MIRROR_DEBIAN}
MIRROR_VOLATILE=${MIRROR_DEBIAN}

DISTRIBUTION="squeeze"

lb config noauto \
	--apt-recommends true \
	--archive-areas "main contrib non-free" \
	--backports false \
	--bootappend-live 'persistent noautologin' \
  --debian-installer live \
	--bootloader syslinux \
	--iso-publisher "GFD Dennou Club; http://www.gfd-dennou.org/;" \
	--linux-flavours 686 \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-binary-volatile ${MIRROR_VOLATILE} \
	--mirror-bootstrap ${MIRROR_BOOTSTRAP} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-chroot-volatile ${MIRROR_VOLATILE} \
	--security true \
	--syslinux-timeout 30 \
	--tasks "japanese japanese-desktop laptop desktop xfce-desktop" \
	--tasksel aptitude \
	--volatile true \
	--win32-loader true \
	-d ${DISTRIBUTION} \
	-l ja \
	-r live.debian.net \
	--syslinux-splash `pwd`/config/binary_syslinux/splash.png \
	${@}
