#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"
MIRROR_BOOTSTRAP=${MIRROR_DEBIAN}

DISTRIBUTION="wheezy"
ARCH="i386"
MODE="debian"
BOOTAPPEND_LIVE="boot=live config persistence splash noautologin locales=ja_JP.UTF-8 keyboard-layouts=jp"

lb config noauto \
	--apt-ftp-proxy http://localhost:3142/ \
	--apt-http-proxy http://localhost:3142/ \
	--apt-recommends true \
	--architecture "${ARCH}" \
	--archive-areas "main contrib non-free" \
	--bootappend-live "${BOOTAPPEND_LIVE}" \
	--debian-installer live \
	--debian-installer-distribution wheezy \
	--debug true \
	--distribution "${DISTRIBUTION}" \
	--firmware-binary true \
	--firmware-chroot true \
	--iso-publisher "GFD Dennou Club; http://www.gfd-dennou.org/;" \
	--mirror-binary "${MIRROR_DEBIAN}" \
	--mirror-binary-security "${MIRROR_SECURITY}" \
	--mirror-bootstrap "${MIRROR_BOOTSTRAP}" \
	--mirror-chroot "${MIRROR_DEBIAN}" \
	--mirror-chroot-security "${MIRROR_SECURITY}" \
	--mode "${MODE}" \
	--win32-loader true \
	${@}
