#---------------------------------------------------------------------
#     Copyright (C) GFD Dennou Club, 2005. All rights reserved.
#---------------------------------------------------------------------
#= Generate HTML from RD
#
# * Yasuhiro MORIKAWA
#   * 2006/03/05 (Yasuhiro MORIKAWA) Created
#
######################################################################

all:
	make -f Makefile.rd2html $@

clean:
	make -f Makefile.rd2html $@

clean.all:
	make -f Makefile.rd2html $@

help:
	make -f Makefile.rd2html $@

dennou:
	make -f Makefile.dennou $@

check:
	make -f Makefile.dennou $@

force:
	make -f Makefile.dennou $@