#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"

lh_config noautoconfig \
	--categories "main" \
	--debian-installer netboot \
	--debian-installer-distribution lenny \
	--distribution lenny \
	--encryption disabled \
	--iso-publisher "Debian JP Project; http://www.debian.or.jp/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--syslinux-timeout 30 \
	${@}
