#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--categories "main" \
	--debian-installer live \
	--debian-installer-distribution sid \
	--iso-publisher "Debian JP Project; http://www.debian.or.jp/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--bootloader syslinux \
	--syslinux-timeout 30 \
	${@}
