#!/bin/sh
MIRROR_DEBIAN="ftp://dennou-k.gfd-dennou.org/arch-large1/cc-env/Linux/debian/"
MIRROR_SECURITY="http://security.debian.org/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--categories "main" \
	--debian-installer live \
	--debian-installer-distribution lenny \
	--iso-publisher "GFD Dennou Club; http://www.gfd-dennou.org/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--bootloader syslinux \
	--syslinux-menu vesamenu \
	--syslinux-timeout 100 \
  --hostname debian-dennou \
  --username liveuser \
	${@}
