:name: division
:description: division a data by the other
:nvars: 2
:script: |
  dat = gphys0 / gphys1

  # NAME CHANGE MUST BE IMPLEMENTED IN GPhys
  dat.name = gphys0.name + "_div_" + gphys1.name
  if gphys0.long_name && gphys1.long_name
    dat.long_name = gphys0.long_name + " / " + gphys1.long_name
  end

  [dat]

:outputs:
- :name: quotient
  :subscript: quot
  :description: quotient of two data
