:name: stddev
:description: the first dimensional standard deviation
:nvars: 1
:script: |
  arg0 = [0] if arg0.empty?
  [gphys0.stddev(*arg0)]

:setting_html: |
  <%= analysis_dimension_selector(0,"stddev") %>

:arguments:
- :description: the dimension for standard deviation 
  :value_type: array_string
  :default: []
  :position: 0
:outputs:
- :name: stddev
  :subscript: stddev
  :description: standard deviation
