:name: subtraction
:description: subtraction a data from the other
:nvars: 2
:script: |
  dat = gphys0 - gphys1

  # NAME CHANGE MUST BE IMPLEMENTED IN GPhys
  dat.name = gphys0.name + "_minus_" + gphys1.name
  if gphys0.long_name && gphys1.long_name
    dat.long_name = gphys0.long_name + " - " + gphys1.long_name
  end

  [dat]

:outputs:
- :name: difference
  :subscript: diff
  :description: difference of two data
