data_path: RAILS_ROOT/data

#other_gfdnavi_servers:
#  - http://localhost:2000/

#remote_data_paths:
#  - http://test.opendap.org/opendap-3.7/nph-dods/data/

#diagram_path: RAILS_ROOT/public/diagrams

user_path: RAILS_ROOT/usr

work_path: RAILS_ROOT/tmp/work

ignored_dirs:
  - !ruby/regexp /^CVS$/i
  - cvsroot

#display:                    # This is obsolete; use 'DISPLAY' in 'env'

debug: true

benchmark: false

disable_user: false

proxy: 

using_proxy: false

allow_any_openid: false

paginate_per: 10

diagram_cache_path: RAILS_ROOT/tmp/diagram_cache

data_cache_path: RAILS_ROOT/tmp/data_cache

google_map_key: ABQIAAAAfkj1xmBThQOFWkus8Ag_gRTJQa0g3IQ9GZqIMmInSLzwtGDKaBRqIpr19_qp5TBIIzBjbp3ONZnCeA     # for localhost:3000

passphrase: rGtKB

cross_search_center_server: http://localhost:3010/display/server_list

secret: You must change me !! (at least 30 characters)

session_duration: 180 # in minute

admin:
  name: Gfdnavi Admin
  email: gfdnavi@localhost.localdomain

enable_email: false
smtp:
  :address: localhost
  :port: 25
  :domain: example.org
  :authentication: :plain

env:
#  DISPLAY: ":99.0"
  RAILS_ENV: production

#------------
# maximum array size to read in onto run-time memory (soft limit).
# unlimited if not set.
#soft_limit_array_size: 2000000

#-------------
# maximum array size to read in onto run-time memory (hard limit).
# unlimited if not set.
#hard_limit_array_size: 5000000

ignored_attributes:
  - _FillValue
  - missing_value
  - valid_min
  - valid_max
  - valid_range
  - add_offset
  - scale_factor

invisible_attributes:
  - description
  - Description
  - textbody
  - actual_range
  - GRIB_id
  - least_significant_digit
  - precision
  - coordinates
  - var_desc
  - level_desc
  - parent_stat

